-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE* O.SALES_AMOUNT) as SALES from PRODUCT as P, OFFLINE_SALE as O
where P.PRODUCT_ID = O.PRODUCT_ID 
group by O.PRODUCT_ID
order by SALES DESC, P.PRODUCT_CODE