-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) as YEAR, MONTH(O.SALES_DATE) as MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) as USERS
from USER_INFO as U join ONLINE_SALE as O 
on U.USER_ID = O.USER_ID
where U.GENDER is not null
group by MONTH(O.SALES_DATE), U.GENDER
order by YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER