-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH ,"%Y-%m-%d") as DATE_OF_BIRTH
    from MEMBER_PROFILE
    where TLNO IS NOT NULL AND DATE_OF_BIRTH LIKE "_____03___" and GENDER = "W"
    ORDER BY MEMBER_ID;
