-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES 
from USED_GOODS_BOARD as B, USED_GOODS_USER as U
where STATUS = "DONE" and USER_ID = WRITER_ID GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;
