-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE from AUTHOR, BOOK 
    where CATEGORY = "경제" && BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    order by PUBLISHED_DATE
